'use strict';
const width = 10;
const height = 5;
const area = width * height;
console.log('value of area:', area);
console.log('type area:', typeof area);
const bill = 30;
const payment = 50;
const change = payment - bill;
console.log('Value of change:', change);
console.log('Type of change:', typeof change);
const quizzes = 85;
const midterm = 90;
const final = 88;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade:', grade);
console.log('Type of grade:', typeof grade);
const firstName = 'Mia';
const lastName = 'Gong';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName:', fullName);
console.log('Type of fullName:', typeof fullName);
const headCount = 300;
const isSparta = headCount === 300;
console.log('Value of isSparta:', isSparta);
console.log('Type of isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('Value of motto:', motto);
console.log('Type of motto:', typeof motto);
